/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codecad.view;

import codecad.controller.ExternalIOController;
import codecad.controller.IDEWindowController;
import com.alee.laf.WebLookAndFeel;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author 5663296
 */
public class IDEWindow extends javax.swing.JFrame {
    private IDEWindowController controller;
    
    /**
     * Creates new form IDE
     */
    public IDEWindow() {
        initComponents();
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
        }
        this.getContentPane().setBackground(Color.WHITE);
        this.setButtonColor(this.botaoAplicar, Color.WHITE, Color.WHITE, new Color(75,0,130), Color.GREEN, new Color(75,0,130), Color.GREEN);
        this.setButtonColor(this.botaoLimpar, Color.WHITE, Color.WHITE, new Color(75,0,130), Color.GREEN, new Color(75,0,130), Color.GREEN);
        this.setButtonColor(this.botaoListar, Color.WHITE, Color.WHITE, new Color(75,0,130), Color.GREEN, new Color(75,0,130), Color.GREEN);
        this.setButtonColor(this.botaoSalvar, Color.WHITE, Color.WHITE, new Color(75,0,130), Color.GREEN, new Color(75,0,130), Color.GREEN);
        this.codeArea.setTabSize(4);
        URL urlIcon = getClass().getResource("/Touhou_Sakuya_Icon.png");
        Image frameIcon = null;
        try {
            frameIcon = ExternalIOController.getImagem(urlIcon);
        } catch (IOException ex) {
            Logger.getLogger(IDEWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setIconImage(frameIcon.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        this.repaint();
        this.controller = new IDEWindowController(this);
    }
    
    private void setButtonColor(com.alee.laf.button.WebButton b, Color fore, Color selFor, Color top, Color topSel, Color bot, Color botSel){
        b.setForeground (fore);
        b.setSelectedForeground (selFor);
        b.setTopBgColor (top);
        b.setTopSelectedBgColor (topSel);
        b.setBottomBgColor (bot);
        b.setBottomSelectedBgColor (botSel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAplicar = new com.alee.laf.button.WebButton();
        painelImagem = new javax.swing.JPanel();
        labelErro = new javax.swing.JLabel();
        botaoListar = new com.alee.laf.button.WebButton();
        botaoLimpar = new com.alee.laf.button.WebButton();
        botaoSalvar = new com.alee.laf.button.WebButton();
        scrollCode = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CodeCAD");
        setMinimumSize(new java.awt.Dimension(700, 700));

        botaoAplicar.setText("Aplicar Código");
        botaoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAplicarActionPerformed(evt);
            }
        });

        painelImagem.setBackground(new java.awt.Color(255, 255, 255));
        painelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), new java.awt.Color(255, 51, 51)));
        painelImagem.setLayout(new java.awt.BorderLayout());

        labelErro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelErro.setForeground(new java.awt.Color(102, 0, 255));
        labelErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoListar.setText("Listar Comandos");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar Imagem");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar Imagem");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        scrollCode.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 102), new java.awt.Color(255, 51, 51)));

        codeArea.setColumns(20);
        codeArea.setFont(new java.awt.Font("Courier New", 0, 22)); // NOI18N
        codeArea.setRows(5);
        codeArea.setText("\ndraw {\n\n}");
        scrollCode.setViewportView(codeArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollCode)
                    .addComponent(labelErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(botaoAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelImagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAplicarActionPerformed
        this.controller.iniciarLeituraCódigo();
    }//GEN-LAST:event_botaoAplicarActionPerformed

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        this.controller.iniciarJanelaListarComandos();
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        this.controller.limparImagem();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        this.controller.iniciarSalvamentoImagem();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDEWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAplicar;
    private com.alee.laf.button.WebButton botaoLimpar;
    private com.alee.laf.button.WebButton botaoListar;
    private com.alee.laf.button.WebButton botaoSalvar;
    private javax.swing.JTextArea codeArea;
    private javax.swing.JLabel labelErro;
    private javax.swing.JPanel painelImagem;
    private javax.swing.JScrollPane scrollCode;
    // End of variables declaration//GEN-END:variables

    public JPanel getPainelImagem() {
        return painelImagem;
    }

    public JLabel getLabelErro() {
        return labelErro;
    }

    public JTextArea getCodeArea() {
        return codeArea;
    }
    
}