/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.codecad.view;

import br.beholder.codecad.controller.IDEWindowController;
import br.beholder.codecad.model.parser.LexicalError;
import br.beholder.codecad.model.parser.Lexico;
import br.beholder.codecad.model.parser.SemanticError;
import br.beholder.codecad.model.parser.Semantico;
import br.beholder.codecad.model.parser.Sintatico;
import br.beholder.codecad.model.parser.SyntaticError;
import com.alee.laf.WebLookAndFeel;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.UnsupportedLookAndFeelException;
import org.syntax.jedit.JEditTextArea;
import org.syntax.jedit.KeywordMap;
import org.syntax.jedit.tokenmarker.CodeCadTokenMarker;
import org.syntax.jedit.tokenmarker.Token;

/**
 *
 * @author 5663296
 */
public class IDEWindow extends javax.swing.JFrame {
    private IDEWindowController controller;
    private JEditTextArea codeArea;
    /**
     * Creates new form IDE
     */
    public IDEWindow() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
        }
        codeArea = new JEditTextArea();
        KeywordMap map = new KeywordMap(true);
        map.add("draw", Token.KEYWORD1);
        map.add("rect", Token.KEYWORD3);
        map.add("elipse", Token.KEYWORD3);
        map.add("line", Token.KEYWORD3);
        map.add("point", Token.KEYWORD3);
        map.add("fill", Token.KEYWORD2);
        map.add("stroke", Token.KEYWORD2);
        map.add("color", Token.KEYWORD2);
        map.add("opacity", Token.KEYWORD2);
        map.add("background", Token.KEYWORD2);
        map.add("display", Token.KEYWORD2);
        codeArea.setTokenMarker(new CodeCadTokenMarker(map));
        codeArea.setText("display 800,600\n" +
"draw{\n" +
"	background 30,30,30\n" +
"	fill 255,255,255\n" +
"	rect 0,0,40,40\n" +
"}");
        textAreaPane.add(codeArea);
//        this.controller = new IDEWindowController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        painelImagem = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textAreaPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botaoListar = new com.alee.laf.button.WebButton();
        botaoLimpar = new com.alee.laf.button.WebButton();
        botaoSalvar = new com.alee.laf.button.WebButton();
        botaoAplicar = new com.alee.laf.button.WebButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CodeCAD");

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.75);

        painelImagem.setBackground(new java.awt.Color(0, 0, 0));
        painelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelImagem.setMinimumSize(new java.awt.Dimension(4, 400));
        painelImagem.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(painelImagem);

        jPanel2.setLayout(new java.awt.BorderLayout());

        textAreaPane.setMinimumSize(new java.awt.Dimension(0, 100));
        textAreaPane.setLayout(new java.awt.BorderLayout());
        jPanel2.add(textAreaPane, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMinimumSize(new java.awt.Dimension(387, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(140, 50));

        botaoListar.setText("Listar Comandos");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoListar);

        botaoLimpar.setText("Limpar Imagem");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLimpar);

        botaoSalvar.setText("Salvar Imagem");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSalvar);

        botaoAplicar.setText("Aplicar Código");
        botaoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAplicarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAplicar);

        jPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAplicarActionPerformed
        this.controller.iniciarLeituraCódigo();
    }//GEN-LAST:event_botaoAplicarActionPerformed

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        this.controller.iniciarJanelaListarComandos();
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        this.painelImagem.removeAll();
        this.painelImagem.revalidate();
        this.repaint();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        this.controller.iniciarSalvamentoImagem();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IDEWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAplicar;
    private com.alee.laf.button.WebButton botaoLimpar;
    private com.alee.laf.button.WebButton botaoListar;
    private com.alee.laf.button.WebButton botaoSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel painelImagem;
    private javax.swing.JPanel textAreaPane;
    // End of variables declaration//GEN-END:variables

    public JPanel getPainelImagem() {
        return painelImagem;
    }

    public JEditTextArea getAreaInputCodigo() {
        return codeArea;
    }


}
