package br.beholder.codecad.model.parser;

public interface ParserConstants
{
    int FIRST_SEMANTIC_ACTION = 39;

    int SHIFT  = 0;
    int REDUCE = 1;
    int ACTION = 2;
    int ACCEPT = 3;
    int GO_TO  = 4;
    int ERROR  = 5;

    int[][] PRODUCTIONS =
    {
        { 23, 2 },
        { 23, 2 },
        { 23, 4 },
        { 24, 7 },
        { 25, 8 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 2 },
        { 26, 0 },
        { 27, 10 },
        { 28, 10 },
        { 29, 4 },
        { 30, 10 },
        { 31, 10 },
        { 32, 4 },
        { 33, 7 },
        { 34, 13 },
        { 35, 13 },
        { 36, 13 },
        { 37, 19 },
        { 38, 16 }
    };

    String[] PARSER_ERROR =
    {
        "Erro estado 0",
        "Erro estado 1",
        "Erro estado 2",
        "Erro estado 3",
        "Erro estado 4",
        "Erro estado 5",
        "Erro estado 6",
        "Erro estado 7",
        "Erro estado 8",
        "Erro estado 9",
        "Erro estado 10",
        "Erro estado 11",
        "Erro estado 12",
        "Erro estado 13",
        "Erro estado 14",
        "Erro estado 15",
        "Erro estado 16",
        "Erro estado 17",
        "Erro estado 18",
        "Erro estado 19",
        "Erro estado 20",
        "Erro estado 21",
        "Erro estado 22",
        "Erro estado 23",
        "Erro estado 24",
        "Erro estado 25",
        "Erro estado 26",
        "Erro estado 27",
        "Erro estado 28",
        "Erro estado 29",
        "Erro estado 30",
        "Erro estado 31",
        "Erro estado 32",
        "Erro estado 33",
        "Erro estado 34",
        "Erro estado 35",
        "Erro estado 36",
        "Erro estado 37",
        "Erro estado 38",
        "Erro estado 39",
        "Erro estado 40",
        "Erro estado 41",
        "Erro estado 42",
        "Erro estado 43",
        "Erro estado 44",
        "Erro estado 45",
        "Erro estado 46",
        "Erro estado 47",
        "Erro estado 48",
        "Erro estado 49",
        "Erro estado 50",
        "Erro estado 51",
        "Erro estado 52",
        "Erro estado 53",
        "Erro estado 54",
        "Erro estado 55",
        "Erro estado 56",
        "Erro estado 57",
        "Erro estado 58",
        "Erro estado 59",
        "Erro estado 60",
        "Erro estado 61",
        "Erro estado 62",
        "Erro estado 63",
        "Erro estado 64",
        "Erro estado 65",
        "Erro estado 66",
        "Erro estado 67",
        "Erro estado 68",
        "Erro estado 69",
        "Erro estado 70",
        "Erro estado 71",
        "Erro estado 72",
        "Erro estado 73",
        "Erro estado 74",
        "Erro estado 75",
        "Erro estado 76",
        "Erro estado 77",
        "Erro estado 78",
        "Erro estado 79",
        "Erro estado 80",
        "Erro estado 81",
        "Erro estado 82",
        "Erro estado 83",
        "Erro estado 84",
        "Erro estado 85",
        "Erro estado 86",
        "Erro estado 87",
        "Erro estado 88",
        "Erro estado 89",
        "Erro estado 90",
        "Erro estado 91",
        "Erro estado 92",
        "Erro estado 93",
        "Erro estado 94",
        "Erro estado 95",
        "Erro estado 96",
        "Erro estado 97",
        "Erro estado 98",
        "Erro estado 99",
        "Erro estado 100",
        "Erro estado 101",
        "Erro estado 102",
        "Erro estado 103",
        "Erro estado 104",
        "Erro estado 105",
        "Erro estado 106",
        "Erro estado 107",
        "Erro estado 108",
        "Erro estado 109",
        "Erro estado 110",
        "Erro estado 111",
        "Erro estado 112",
        "Erro estado 113",
        "Erro estado 114",
        "Erro estado 115",
        "Erro estado 116",
        "Erro estado 117",
        "Erro estado 118",
        "Erro estado 119",
        "Erro estado 120",
        "Erro estado 121",
        "Erro estado 122",
        "Erro estado 123",
        "Erro estado 124",
        "Erro estado 125",
        "Erro estado 126",
        "Erro estado 127",
        "Erro estado 128",
        "Erro estado 129",
        "Erro estado 130",
        "Erro estado 131",
        "Erro estado 132",
        "Erro estado 133",
        "Erro estado 134",
        "Erro estado 135",
        "Erro estado 136",
        "Erro estado 137",
        "Erro estado 138",
        "Erro estado 139",
        "Erro estado 140",
        "Erro estado 141",
        "Erro estado 142",
        "Erro estado 143",
        "Erro estado 144",
        "Erro estado 145",
        "Erro estado 146",
        "Erro estado 147",
        "Erro estado 148",
        "Erro estado 149",
        "Erro estado 150",
        "Erro estado 151",
        "Erro estado 152",
        "Erro estado 153",
        "Erro estado 154",
        "Erro estado 155",
        "Erro estado 156",
        "Erro estado 157",
        "Erro estado 158",
        "Erro estado 159",
        "Erro estado 160",
        "Erro estado 161",
        "Erro estado 162",
        "Erro estado 163",
        "Erro estado 164",
        "Erro estado 165",
        "Erro estado 166",
        "Erro estado 167",
        "Erro estado 168",
        "Erro estado 169",
        "Erro estado 170",
        "Erro estado 171",
        "Erro estado 172",
        "Erro estado 173",
        "Erro estado 174",
        "Erro estado 175",
        "Erro estado 176",
        "Erro estado 177"
    };
}
